### ISSUE TITLE
How to compile on Ubuntu 18.04

### ISSUE THREAD

**Issue by bashanbro** [jameskermode/AtomEye#6]
Dear Sir:
Many thanks for your great JOB. I was trying to compile on my Ubuntu 18.04 System, all the related lib had been install. And I got the follwing errors:

gcc -DHAVE_NETCDF -DNETCDF4 -fPIC -O3 -D_  -I../include -I.. -I. -DUSE_CUI  A.o primitives.o viewport.o utils.o xtal_shift.o info.o rcut_patch.o scratch.o geo.o LeastSquareStrain.o cui.o cui_AX.o  -o A -L../lib -lAX -lAtoms -lVecMat3 -lVecMat -lIO -lScalar -lTimer  -lm -lXpm -lXext -lX11 -lpng -lz -ljpeg -lhistory -lncurses -lreadline -lcurl -L/usr/local/lib/ -lnetcdf -lpthread -L/home/ba/Documents/libra/lapack -llapacke -lcblas 
../lib/libAX.a(AX.o): In function `AX_save_pixmap_as_eps':
AX.c:(.text+0x1cf6): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
../lib/libVecMat3.a(M3diag.o): In function `M3Diag':
M3diag.c:(.text+0x268f): undefined reference to `dsyev_'
collect2: error: ld returned 1 exit status
Makefile:53: recipe for target 'A' failed
make[2]: *** [A] Error 1
make[2]: Leaving directory '/home/ba/Documents/tools/AtomEyeCM/A3'
Makefile.atomeye:34: recipe for target 'subdirs' failed
make[1]: *** [subdirs] Error 1
make[1]: Leaving directory '/home/ba/Documents/tools/AtomEyeCM'
Makefile:18: recipe for target 'all' failed
make: *** [all] Error 2

Could you give me some suggestions?  Thanks again.

**Comment by bashanbro** [comment]
Dear Sir:
I have found the problem, the reason were the libblas and liblapack. I tried the following cmd in the terminal:
sudo apt-get install libblas-dev liblapack-dev

And then ran:
make clean
make

Everything was OK!

MANY THANKS again!
